/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;
import javax.swing.JOptionPane;
import Koneksi.koneksi;
import Koneksi.koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;

/**
 *
 * @author Lenovo
 */
public class HALAMAN_TAMBAH extends javax.swing.JFrame {
    Koneksi.koneksi k = new koneksi();
   
    

    /**
     * Creates new form HALAMAN
     */
    public HALAMAN_TAMBAH() {
        initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        k.koneksi();
    }

    
//    private void jafung(){
//    kategori.removeAllItems();
//    kategori.addItem("Pilih Golongan/Pangkat");
//    kategori.addItem("Belum ada");}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        lokasi = new javax.swing.JTextField();
        BtnPilih = new javax.swing.JToggleButton();
        tanggal = new com.toedter.calendar.JDateChooser();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnkeluar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnLhat = new javax.swing.JButton();
        labelhome = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        labelhome1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        labelhome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 252, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(920, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(34, 50, 91));
        jLabel1.setFont(new java.awt.Font("Meiryo UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 50, 91));
        jLabel1.setText("Tambah Data");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 50, 91));
        jLabel6.setText("Nama Dokumen");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 50, 91));
        jLabel3.setText("Deskripsi Dokumen");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 50, 91));
        jLabel4.setText("Lokasi Dokumen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 50, 91));
        jLabel7.setText("Tanggal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
        jPanel1.add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 280, 30));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 280, 30));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Save.png"))); // NOI18N
        btnSave.setText("SIMPAN");
        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, 90));

        jLabel2.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 50, 91));
        jLabel2.setText("Kode Dokumen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Resmi", "Pribadi" }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });
        jPanel1.add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 140, 30));

        jLabel8.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 50, 91));
        jLabel8.setText("Kategori Dokumen");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        deskripsi.setColumns(20);
        deskripsi.setRows(5);
        jScrollPane1.setViewportView(deskripsi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 280, 100));
        jPanel1.add(lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 130, 30));

        BtnPilih.setText("Browser");
        BtnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 80, 30));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 30));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Untitled-1.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 820, 520));

        jPanel2.setBackground(new java.awt.Color(34, 50, 91));
        jPanel2.setInheritsPopupMenu(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnkeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Logout_37127.png"))); // NOI18N
        btnkeluar.setBorder(null);
        btnkeluar.setBorderPainted(false);
        btnkeluar.setContentAreaFilled(false);
        btnkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnkeluar.setMaximumSize(new java.awt.Dimension(250, 261));
        btnkeluar.setMinimumSize(new java.awt.Dimension(250, 261));
        btnkeluar.setPreferredSize(new java.awt.Dimension(250, 261));
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 40, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Logout");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        btnLhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/folder.png"))); // NOI18N
        btnLhat.setBorder(null);
        btnLhat.setContentAreaFilled(false);
        btnLhat.setMaximumSize(new java.awt.Dimension(250, 261));
        btnLhat.setMinimumSize(new java.awt.Dimension(250, 261));
        btnLhat.setPreferredSize(new java.awt.Dimension(250, 2611));
        btnLhat.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        btnLhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLhatActionPerformed(evt);
            }
        });
        jPanel2.add(btnLhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 50, 50));

        labelhome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelhome.setForeground(new java.awt.Color(255, 255, 255));
        labelhome.setText("Lihat Data");
        labelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhomeMouseClicked(evt);
            }
        });
        jPanel2.add(labelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setContentAreaFilled(false);
        btnHome.setMaximumSize(new java.awt.Dimension(250, 261));
        btnHome.setMinimumSize(new java.awt.Dimension(250, 261));
        btnHome.setPreferredSize(new java.awt.Dimension(250, 2611));
        btnHome.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 50));

        labelhome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelhome1.setForeground(new java.awt.Color(255, 255, 255));
        labelhome1.setText("Home");
        labelhome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhome1MouseClicked(evt);
            }
        });
        jPanel2.add(labelhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 70, 40, -1));

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/tambah.png"))); // NOI18N
        btnTambah.setBorder(null);
        btnTambah.setContentAreaFilled(false);
        btnTambah.setMaximumSize(new java.awt.Dimension(250, 261));
        btnTambah.setMinimumSize(new java.awt.Dimension(250, 261));
        btnTambah.setPreferredSize(new java.awt.Dimension(250, 2611));
        btnTambah.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel2.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 50));

        labelhome2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelhome2.setForeground(new java.awt.Color(255, 255, 255));
        labelhome2.setText("Tambah Data");
        labelhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhome2MouseClicked(evt);
            }
        });
        jPanel2.add(labelhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(this.tanggal.getDate()));
        
        try {
            k.stat.executeUpdate("insert into arsip_dokumen values ("+"'"+kode.getText()+"',"
                + "'"+nama.getText()+"',"
                + "'"+kategori.getSelectedItem()+"',"
                + "'"+lokasi.getText()+"',"
                + "'"+deskripsi.getText()+"',"
                + "'"+tanggal+"')");
            kode.setText("");
            nama.setText("");
            kategori.setSelectedItem(" ");
            lokasi.setText("");
            deskripsi.setText("");
            kode.requestFocus();
            JOptionPane.showMessageDialog(rootPane,"Data tersimpan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriActionPerformed

    private void BtnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser OpenFile = new JFileChooser();
        OpenFile.showOpenDialog(null);
        File x_file = OpenFile.getSelectedFile();
        String NamaFile = x_file.getAbsolutePath();
        lokasi.setText(NamaFile);
    }//GEN-LAST:event_BtnPilihActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        new Login().show();
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Login().show();
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void labelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMouseClicked
        // TODO add your handling code here:
           new Login().show();
        dispose();
    }//GEN-LAST:event_labelhomeMouseClicked

    private void labelhome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhome1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelhome1MouseClicked

    private void labelhome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhome2MouseClicked
        // TODO add your handling code here:
        new Home().show();
        dispose();
    }//GEN-LAST:event_labelhome2MouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new Home().show();
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        new HALAMAN_TAMBAH().show();
        dispose();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnLhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLhatActionPerformed
        // TODO add your handling code here:
        new Lihat().show();
        dispose();
        
    }//GEN-LAST:event_btnLhatActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HALAMAN_TAMBAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HALAMAN_TAMBAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HALAMAN_TAMBAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HALAMAN_TAMBAH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HALAMAN_TAMBAH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnPilih;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLhat;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JTextArea deskripsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategori;
    private javax.swing.JTextField kode;
    private javax.swing.JLabel labelhome;
    private javax.swing.JLabel labelhome1;
    private javax.swing.JLabel labelhome2;
    private javax.swing.JTextField lokasi;
    private javax.swing.JTextField nama;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
