/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;
import Koneksi.*;
import javax.swing.JOptionPane;
import Koneksi.koneksi;
import Koneksi.koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;

/**
 *
 * @author Lenovo
 */
public class Home extends javax.swing.JFrame {
    Koneksi.koneksi k = new koneksi();
   
    

    /**
     * Creates new form HALAMAN
     */
    public Home() {
        initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        k.koneksi();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnkeluar = new javax.swing.JButton();
        jLogout = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelhome = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        labelhome1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        labelhome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 252, 250));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(920, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(34, 50, 91));
        jLabel1.setFont(new java.awt.Font("Meiryo UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 50, 91));
        jLabel1.setText("SELAMAT DATANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Untitled-1.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 820, 510));

        jPanel2.setBackground(new java.awt.Color(34, 50, 91));
        jPanel2.setInheritsPopupMenu(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnkeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Logout_37127.png"))); // NOI18N
        btnkeluar.setBorder(null);
        btnkeluar.setBorderPainted(false);
        btnkeluar.setContentAreaFilled(false);
        btnkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnkeluar.setMaximumSize(new java.awt.Dimension(250, 261));
        btnkeluar.setMinimumSize(new java.awt.Dimension(250, 261));
        btnkeluar.setPreferredSize(new java.awt.Dimension(250, 261));
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 40, 40));

        jLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLogout.setText("Logout");
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        jPanel2.add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/folder.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(250, 261));
        jButton1.setMinimumSize(new java.awt.Dimension(250, 261));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 2611));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 50, 50));

        labelhome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelhome.setForeground(new java.awt.Color(255, 255, 255));
        labelhome.setText("Lihat Data");
        labelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhomeMouseClicked(evt);
            }
        });
        jPanel2.add(labelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setContentAreaFilled(false);
        btnHome.setMaximumSize(new java.awt.Dimension(250, 261));
        btnHome.setMinimumSize(new java.awt.Dimension(250, 261));
        btnHome.setPreferredSize(new java.awt.Dimension(250, 2611));
        btnHome.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 50));

        labelhome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelhome1.setForeground(new java.awt.Color(255, 255, 255));
        labelhome1.setText("Home");
        labelhome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhome1MouseClicked(evt);
            }
        });
        jPanel2.add(labelhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 70, 40, -1));

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/tambah.png"))); // NOI18N
        btnTambah.setBorder(null);
        btnTambah.setContentAreaFilled(false);
        btnTambah.setMaximumSize(new java.awt.Dimension(250, 261));
        btnTambah.setMinimumSize(new java.awt.Dimension(250, 261));
        btnTambah.setPreferredSize(new java.awt.Dimension(250, 2611));
        btnTambah.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarr/Home.png"))); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel2.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 50));

        labelhome2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelhome2.setForeground(new java.awt.Color(255, 255, 255));
        labelhome2.setText("Tambah Data");
        labelhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhome2MouseClicked(evt);
            }
        });
        jPanel2.add(labelhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        new Login().show();
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
        new Login().show();
        dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void labelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMouseClicked
        // TODO add your handling code here:
           new Lihat().show();
        dispose();
    }//GEN-LAST:event_labelhomeMouseClicked

    private void labelhome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhome1MouseClicked
        // TODO add your handling code here:
        new Home().show();
        dispose();
    }//GEN-LAST:event_labelhome1MouseClicked

    private void labelhome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhome2MouseClicked
        // TODO add your handling code here:
        new HALAMAN_TAMBAH().show();
        dispose();
    }//GEN-LAST:event_labelhome2MouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new Home().show();
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        new HALAMAN_TAMBAH().show();
        dispose();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           new Lihat().show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelhome;
    private javax.swing.JLabel labelhome1;
    private javax.swing.JLabel labelhome2;
    // End of variables declaration//GEN-END:variables
}
